exports.medicationsTextHeaders = ["Medication", "Brand Name", "Dose Quantity", "Rate Quantity", "Frequency of Intakes", "Route of Administration", "Medical Instruction", "Description", "Onset Date", "End Date", "Number of fills"];
exports.allergiesTextHeaders = ["Substance", "Overall Severity", "Reaction", "Reaction Severity", "Status"];
exports.problemsTextHeaders = ["Observation", "Onset Date", "Description", "Severity", "Status"];
exports.proceduresHeaders = ['Service', 'Procedure code', 'Service date', 'Servicing provider', 'Phone#'];
exports.encountersHeaders = ['Type', 'Facility', 'Date of Service', 'Diagnosis/Complaint'];
exports.payersHeaders = ['Payer Name', 'Group ID', 'Member ID', 'Eligibility Start Date', 'Eligibility End Date'];
exports.immunizationsHeaders = ["Immunization", "Brand Name", "Dose Quantity", "Route of Administration", "Approach Site", "Date", "Not Performed", "Description"];
exports.resultsHeaders = ['Test', 'Result', 'Units', 'Ref low', 'Ref high', 'Date', 'Source'];
exports.planOfCareHeaders = ['Program', 'Start Date', 'Severity', ''];
